# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZYFPullRefreshView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'MJRefresh'   

  # Pods for ZYFPullRefreshView

  target 'ZYFPullRefreshViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZYFPullRefreshViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
